### ISSUE TITLE
Support for OpenAI BETA API - Assistants, Threads, etc.

### ISSUE THREAD

**Issue by dgolda** [softwaremill/sttp-openai#151]
I'm adding support for Beta features like Assistants and Threads.

https://platform.openai.com/docs/api-reference/assistants

I'm wondering if the new methods should only be added to OpenAI and OpenAISyncClient, or should they be in a separate trait or class?

Any tips?

My work in progress:
https://github.com/dgolda/sttp-openai/tree/151-support-for-assistants

I noticed that the class naming is inconsistent - which names can be considered exemplary?

**Comment by adamw** [comment]
Ah that's great, the OpenAI API is in constant flux :)

Yes, I think these are the two places that need modifying. Plus any required payload classes in the `requests` package

**Comment by DybekK** [comment]
Thank you for your contribution! Your pull request has been merged :)
