### ISSUE TITLE
Current models like Gpt4o-mini are not supported.

### ISSUE THREAD

**Issue by nemoo** [softwaremill/sttp-openai#187]
Current models like Gpt4o-mini are not supported. And since ChatCompletionModel  is a sealed class it seems that I cannot even create a ChatCompletionModel("gpt-4o-mini") on the fly?

https://github.com/softwaremill/sttp-openai/blob/5492e74c8d5a0e5ed372891c0193be83aac7ee4c/core/src/main/scala/sttp/openai/requests/completions/chat/ChatRequestBody.scala#L113

**Comment by benzwreck** [comment]
I guess https://github.com/softwaremill/sttp-openai/blob/5492e74c8d5a0e5ed372891c0193be83aac7ee4c/core/src/main/scala/sttp/openai/requests/completions/chat/ChatRequestBody.scala#L146 is something you're looking for.

**Comment by nemoo** [comment]
@benzwreck ah yes, thanks! 

Using `model = ChatCompletionModel.CustomChatCompletionModel("gpt-4o-mini")` works for me until the next release.

**Comment by adamw** [comment]
@nemoo maybe you could create a PR which would update the constants that we have? Maybe we should amend the docs as well to cover this :)

**Comment by nemoo** [comment]
@adamw sure, I will provide a PR

**Comment by nemoo** [comment]
PR for the new model and hint in docs: https://github.com/softwaremill/sttp-openai/pull/189

I was not able to test it though, because I cannot get the sbt build to run under Windows unfortunately.

**Comment by nemoo** [comment]
merged and available as of release 0.2.1
