### ISSUE TITLE
JSON schema support

### ISSUE THREAD

**Issue by mrdziuban** [softwaremill/sttp-openai#216]
Would you consider adding support for the [`json_schema` response format](https://platform.openai.com/docs/guides/structured-outputs/how-to-use?context=without_parse)? If so, I would be happy to take a stab at a pull request to add it. I would model it similarly to this: https://github.com/cequence-io/openai-scala-client/blob/master/openai-core/src/main/scala/io/cequence/openaiscala/domain/JsonSchema.scala

**Comment by adamw** [comment]
Sounds great!

As I understand, as a user I would be able to provide the JSON Schema, to which the response should adhere? An extension to this idea would be to derive a Tapir schema from a case class, and then [serialize it as JSON Schema](https://tapir.softwaremill.com/en/latest/docs/json-schema.html). 

And a second extension to that would be to use e.g. jsoniter to deserialize the response to the desired object
