### ISSUE TITLE
How to change request timeout for createChatCompletion

### ISSUE THREAD

**Issue by nemoo** [softwaremill/sttp-openai#219]
I am using the chat completion function like so: `val response: ChatResponse = openAI.createChatCompletion(chatRequestBody)`

When I run it against the current top model, 'p1-preview', I run into 30 second timeouts. '01-preview' is designed to take longer to reason, so it is ok if it takes longer.

The timeout I get: `java.util.concurrent.TimeoutException: test timed out after 30 seconds`

I did not find a parameter on 'createChatCompletion' to increase the timeout. How to do it?

edit: By using a DefaultSyncBackend I can adjust the connection timeout: `val backend = DefaultSyncBackend(BackendOptions.connectionTimeout(5.minutes))`

But that does not help in my case, because I need a larger request timeout.

**Comment by nemoo** [comment]
Thanks!  
I am using this 'openAI':  
```
val openAI: OpenAISyncClient = OpenAISyncClient(apiKey)
val response: ChatResponse = openAI.createChatCompletion(chatRequestBody)
```
It seems to me that OpenAISyncClient returns a ChatResponse:
https://github.com/softwaremill/sttp-openai/blob/master/core/src/main/scala/sttp/openai/OpenAISyncClient.scala#L185

And function readTimeout is not a member of sttp.openai.requests.completions.chat.ChatRequestResponseData.ChatResponse?

**Comment by nemoo** [comment]
Interesting. I am now performing the call using your exact code snippet and I still get this timeout: `java.util.concurrent.TimeoutException: test timed out after 30 seconds`

**Comment by nemoo** [comment]
but I am using it in a test case. Will try outside of test case

**Comment by adamw** [comment]
See 220
